spring.application.name=roomezy-backend

#Swagger
springdoc.api-docs.path=/api-docs

#POstgres
spring.datasource.url=jdbc:postgresql://localhost:5432/roomezybackend
spring.datasource.username=postgres
spring.datasource.password=12345

#Spring Data JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
